version: 1.0.{build}
branches:
  only:
  - with_hide
version: 1.0.{build}
environment:
    nodejs_version: 10
install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    # install modules
    - npm ci
build: on
platform:
    - x64
before_package: echo Before package
test_script:
    - npm run dist